// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnvpwaHCKEVhde50MF1IDVmmw0dvi47R4',
    appId: '1:796024580733:web:271ea5d3529c5ad45c5f14',
    messagingSenderId: '796024580733',
    projectId: 'findmykid-b9bb5',
    authDomain: 'findmykid-b9bb5.firebaseapp.com',
    storageBucket: 'findmykid-b9bb5.appspot.com',
    measurementId: 'G-RT4GSRBCWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYyKt2iwphWy9C0SLaaoFfnV4KPJn0Lmo',
    appId: '1:796024580733:android:02c093a4a8f535bb5c5f14',
    messagingSenderId: '796024580733',
    projectId: 'findmykid-b9bb5',
    storageBucket: 'findmykid-b9bb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApu6mNcVcKc4ROcXFf4QUVeV-flIRnaNA',
    appId: '1:796024580733:ios:e69a567a6e5fde895c5f14',
    messagingSenderId: '796024580733',
    projectId: 'findmykid-b9bb5',
    storageBucket: 'findmykid-b9bb5.appspot.com',
    iosClientId: '796024580733-8v6t0360h1pd9o6qh3v9aok3fmppvrom.apps.googleusercontent.com',
    iosBundleId: 'com.example.appParent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApu6mNcVcKc4ROcXFf4QUVeV-flIRnaNA',
    appId: '1:796024580733:ios:e69a567a6e5fde895c5f14',
    messagingSenderId: '796024580733',
    projectId: 'findmykid-b9bb5',
    storageBucket: 'findmykid-b9bb5.appspot.com',
    iosClientId: '796024580733-8v6t0360h1pd9o6qh3v9aok3fmppvrom.apps.googleusercontent.com',
    iosBundleId: 'com.example.appParent',
  );
}
